# Generated by Django 5.2.6 on 2025-09-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('Natural Science', 'Natural Science'), ('Social Science', 'Social Science')], default='Natural Science', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Ministry', 'Ministry Exam'), ('Matric', 'Matric Exam'), ('Entrance', 'Entrance Exam')], default='Ministry', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('Video', 'Video Resource')], default='PDF', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_exam.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_exam.examtype')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_exam.resourcetype')),
            ],
        ),
    ]
