# Generated by Django 5.2.6 on 2025-09-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college',
            new_name='college_type',
        ),
    ]
