# Generated by Django 5.2.6 on 2025-09-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0003_gradeeightresource_gradeelevenresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeeightresource',
            name='file',
            field=models.FileField(max_length=255, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='gradeelevenresource',
            name='file',
            field=models.FileField(max_length=255, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='gradesixresource',
            name='file',
            field=models.FileField(max_length=255, upload_to='resources/'),
        ),
    ]
