# Generated by Django 5.2.6 on 2025-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0004_alter_gradeeightresource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSixTotalSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Civics', 'Civics')], default='Mathematics', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gradesixresource',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Civics', 'Civics')], default='Mathematics'),
        ),
    ]
