# Generated by Django 5.2.6 on 2025-10-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0005_gradesixtotalsubjects_alter_gradesixresource_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesixtotalsubjects',
            old_name='subject',
            new_name='alsubjects',
        ),
    ]
