# Generated by Django 5.2.6 on 2025-10-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0006_rename_subject_gradesixtotalsubjects_alsubjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesixtotalsubjects',
            old_name='alsubjects',
            new_name='allsubjects',
        ),
    ]
