# Generated by Django 5.2.6 on 2025-10-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0007_rename_alsubjects_gradesixtotalsubjects_allsubjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesixtotalsubjects',
            old_name='allsubjects',
            new_name='allsubject',
        ),
    ]
