# Generated by Django 5.2.6 on 2025-10-04 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0008_rename_allsubjects_gradesixtotalsubjects_allsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesixtotalsubjects',
            name='description',
            field=models.TextField(default='No description provided.', max_length=255),
        ),
        migrations.AddField(
            model_name='gradesixtotalsubjects',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gradesixtotalsubjects',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
