# Generated by Django 5.2.6 on 2025-10-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0009_gradesixtotalsubjects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesixresource',
            name='teacher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
