# Generated by Django 5.2.6 on 2025-10-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_exam', '0010_gradesixresource_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesixresource',
            name='teacher',
            field=models.CharField(max_length=100),
        ),
    ]
